### ISSUE TITLE
Page SEO

### ISSUE THREAD

**Issue by yourmomgoestocollege** [kthornbloom/JACKRABBIT-APP#2]
Currently there is a suggested max character number for page titles, although I'm not sure why, and moreso why it's set to 55. I've mentioned before that we need to list a suggested character number and character count for the Page Browser Title and Page Description. For the Page Browser Title the max should be 60, and for the Page Description it should be 160 characters.

**Comment by kthornbloom** [comment]
Who is "your mom goes to college"?? Lol

Anyway, limits are set because different search engines accept different numbers of characters, so the limit should account for the smallest one.

Each SEO field already has max and current character counts, as well as a warning for empty fields.
